project = "simartar-proj-03"
region  = "northamerica-northeast1"
zone    = "northamerica-northeast1-a"
image   = "projects/fortigcp-project-001/global/images/fortinet-fgtondemand-647-20210907-001-w-license"
machine = "n1-standard-4"